# Generated by Django 5.0.3 on 2024-04-05 03:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_herobiz_ds', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfolio',
            name='client',
            field=models.CharField(blank=True, max_length=20, verbose_name='Client'),
        ),
    ]
