
# This file was generated by 'versioneer.py' (0.29) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2024-06-19T09:26:47-0700",
 "dirty": true,
 "error": null,
 "full-revisionid": "553d8d46217af8e751dc543ffc5e9f3dacd2487a",
 "version": "0.1.2"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
