
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2024-06-19T18:32:10+0100",
 "dirty": false,
 "error": null,
 "full-revisionid": "378eb100c02ca0e830e4b5203fd20edf9cd23127",
 "version": "0.5.35"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
