# Generated by Django 4.2.5 on 2023-12-07 06:01

import django.core.validators
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('username', models.CharField(db_column='USERNAME', db_index=True, max_length=255, unique=True)),
                ('email', models.EmailField(db_column='EMAIL', db_index=True, max_length=254, unique=True)),
                ('first_name', models.CharField(blank=True, db_column='FIRST_NAME', max_length=255, null=True)),
                ('last_name', models.CharField(blank=True, db_column='LAST_NAME', max_length=255, null=True)),
                ('mobile_number', models.CharField(blank=True, db_column='MOBILE_NUMBER', db_index=True, max_length=15, null=True, unique=True, validators=[django.core.validators.RegexValidator(code='invalid_mobile_number', message='Mobile number must be 10 to 15 digits long and contain only digits.', regex='^\\d{10,15}$')])),
                ('is_active', models.BooleanField(db_column='IS_ACTIVE', default=True)),
                ('is_default', models.BooleanField(db_column='IS_DEFAULT', default=False)),
                ('is_deleted', models.BooleanField(db_column='IS_DELETED', default=False)),
                ('date_joined', models.DateTimeField(db_column='DATE_JOINED', default=django.utils.timezone.now)),
                ('password', models.CharField(db_column='PASSWORD', max_length=128)),
            ],
            options={
                'db_table': 'users',
            },
        ),
    ]
