
# This file was generated by 'versioneer.py' (0.29) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2024-06-21T11:02:15-0400",
 "dirty": false,
 "error": null,
 "full-revisionid": "941b2964fe86653f0e9e8ea276d808882969d01d",
 "version": "0.4.32"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
