
# This file was generated by 'versioneer.py' (0.23) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2024-06-19T05:39:23+0000",
 "dirty": false,
 "error": null,
 "full-revisionid": "af3870c268d51d87a45b3f9b90fc21d88b620f76",
 "version": "1.27.0.post0.dev30"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
