
# This file was generated by 'versioneer.py' (0.19) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2024-06-20T17:54:37+0200",
 "dirty": false,
 "error": null,
 "full-revisionid": "9b4b4ca2cbbba913dbb80cd3983e85dffd459647",
 "version": "2.6.0"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
