randomness_boosters = [
    "Be creative.",
    "Be unconventional.",
    "Think outside the box.",
    "Take a novel approach.",
    "Imagine something unique.",
    "Surprise me.",
    "Go wild.",
    "Be original.",
    "Defy expectations.",
    "Be unpredictable.",
    "Innovate.",
    "Astonish me.",
    "Unleash your creativity.",
    "Think differently.",
    "Break the mold.",
    "Be inventive.",
    "Avoid the obvious.",
    "Explore uncharted territory.",
    "Challenge convention.",
    "Embrace the unexpected.",
    "Let your imagination run free.",
    "Conjure up something extraordinary.",
    "Dive into the realm of the unconventional.",
    "Stray from the beaten path.",
    "Shatter preconceptions.",
    "Transcend the ordinary.",
    "Venture into the unknown.",
    "Create something the world has never seen before.",
    "Embrace the power of unconventional thinking.",
    "Unleash a torrent of originality upon the world.",
]

grounding_phrase = "Ensure your response is relevant and focused to the subtopic and field at large, while being creative."

indirect_question_generators = [
"Write a question that can only be answered by an expert in the subtopic, without mentioning the subtopic directly.",
"Craft a question that requires specialized knowledge of the subtopic, but doesn't explicitly reference it.",
"Generate a question that tests the depth of understanding in the subtopic, while avoiding its mention.",
"Compose a question that demands expertise in the subtopic, without making direct references to it.",
"Create a question that assesses proficiency in the subtopic, while circumventing its explicit mention.",
"Develop a question that necessitates a mastery of the subtopic, without specifically naming it.",
"Produce a question that evaluates comprehension of the subtopic, while sidestepping its direct citation.",
"Form a question that requires an intimate knowledge of the subtopic, without overtly alluding to it.",
"Devise a question that probes expertise in the subtopic, while eschewing its explicit reference.",
"Construct a question that demands a deep grasp of the subtopic, without expressly invoking it.",
"Fashion a question that assesses command of the subtopic, while circumnavigating its direct mention.",
"Formulate a question that tests proficiency in the subtopic, without specifically referencing it.",
"Shape a question that requires a thorough understanding of the subtopic, while avoiding its explicit invocation.",
"Build a question that necessitates expertise in the subtopic, without directly mentioning it.",
"Create a question that demands specialized insight into the subtopic, while sidestepping its overt reference.",
"Craft a question that probes mastery of the subtopic, without explicitly citing it.",
"Compose a question that assesses expertise in the subtopic, while circumventing its direct mention.",
"Generate a question that evaluates understanding of the subtopic, without expressly naming it.",
"Develop a question that requires a deep knowledge of the subtopic, while avoiding its explicit invocation.",
"Produce a question that tests command of the subtopic, without overtly alluding to it.",
"Form a question that demands proficiency in the subtopic, while eschewing its direct reference.",
"Devise a question that assesses mastery of the subtopic, without specifically invoking it.",
"Fashion a question that necessitates a thorough grasp of the subtopic, while circumnavigating its explicit mention.",
"Construct a question that requires specialized knowledge of the subtopic, without expressly referencing it.",
"Shape a question that probes expertise in the subtopic, while sidestepping its direct citation.",
"Build a question that evaluates proficiency in the subtopic, without explicitly naming it.",
"Create a question that demands a deep understanding of the subtopic, while avoiding its overt invocation.",
"Craft a question that assesses command of the subtopic, without directly mentioning it.",
"Compose a question that requires intimate knowledge of the subtopic, while circumventing its explicit reference.",
"Generate a question that tests mastery of the subtopic, without expressly invoking it."
]