from datasurface.handler.cicd import RepositorywithCICD as RepositorywithCICD
from datasurface.md.GitOps import GitHubRepository as GitHubRepository, Repository as Repository
from datasurface.md.Lint import ValidationTree as ValidationTree

class GitHubCICD(RepositorywithCICD):
    def __init__(self, name: str) -> None: ...
    def __eq__(self, other: object) -> bool: ...
    def __hash__(self) -> int: ...
    def createRepositoryForPullRequestRepo(self) -> Repository: ...
