import abc
from _typeshed import Incomplete
from abc import ABC, abstractmethod
from datasurface.md.GitOps import Repository as Repository
from datasurface.md.Governance import Ecosystem as Ecosystem
from datasurface.md.Lint import ValidationTree as ValidationTree

class RepositorywithCICD(ABC, metaclass=abc.ABCMeta):
    name: Incomplete
    def __init__(self, name: str) -> None: ...
    def __eq__(self, other: object) -> bool: ...
    def __hash__(self) -> int: ...
    @abstractmethod
    def createRepositoryForPullRequestRepo(self) -> Repository: ...
    def getEcosystem(self, path: str) -> Ecosystem | None: ...
    def verifyPullRequest(self, mainFolder: str, prFolder: str) -> ValidationTree: ...
