
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2024-06-21T10:41:21-0400",
 "dirty": false,
 "error": null,
 "full-revisionid": "d38e30cade1dd777716f49b98fec62a739803dc6",
 "version": "2024.6.21.1"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
