
# This file was generated by 'versioneer.py' (0.21) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2024-06-20T14:05:06+0200",
 "dirty": false,
 "error": null,
 "full-revisionid": "d6dd41fc298de6c3c5a59db40de6fb3d78ad92b2",
 "version": "3.0.3"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
