# coding: utf-8

"""
    Femsa API

    Femsa sdk

    The version of the OpenAPI document: 2.1.0
    Contact: engineering@femsa.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from digitalfemsa.api.companies_api import CompaniesApi


class TestCompaniesApi(unittest.TestCase):
    """CompaniesApi unit test stubs"""

    def setUp(self) -> None:
        self.api = CompaniesApi()

    def tearDown(self) -> None:
        pass

    def test_get_companies(self) -> None:
        """Test case for get_companies

        Get List of Companies
        """
        pass

    def test_get_company(self) -> None:
        """Test case for get_company

        Get Company
        """
        pass


if __name__ == '__main__':
    unittest.main()
