# coding: utf-8

"""
    Femsa API

    Femsa sdk

    The version of the OpenAPI document: 2.1.0
    Contact: engineering@femsa.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from digitalfemsa.api.products_api import ProductsApi


class TestProductsApi(unittest.TestCase):
    """ProductsApi unit test stubs"""

    def setUp(self) -> None:
        self.api = ProductsApi()

    def tearDown(self) -> None:
        pass

    def test_orders_create_product(self) -> None:
        """Test case for orders_create_product

        Create Product
        """
        pass

    def test_orders_delete_product(self) -> None:
        """Test case for orders_delete_product

        Delete Product
        """
        pass

    def test_orders_update_product(self) -> None:
        """Test case for orders_update_product

        Update Product
        """
        pass


if __name__ == '__main__':
    unittest.main()
