# coding: utf-8

"""
    Femsa API

    Femsa sdk

    The version of the OpenAPI document: 2.1.0
    Contact: engineering@femsa.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from digitalfemsa.api.shippings_api import ShippingsApi


class TestShippingsApi(unittest.TestCase):
    """ShippingsApi unit test stubs"""

    def setUp(self) -> None:
        self.api = ShippingsApi()

    def tearDown(self) -> None:
        pass

    def test_orders_create_shipping(self) -> None:
        """Test case for orders_create_shipping

        Create Shipping
        """
        pass

    def test_orders_delete_shipping(self) -> None:
        """Test case for orders_delete_shipping

        Delete Shipping
        """
        pass

    def test_orders_update_shipping(self) -> None:
        """Test case for orders_update_shipping

        Update Shipping
        """
        pass


if __name__ == '__main__':
    unittest.main()
