from enum import Enum


class DemoResultAllCheckTypes(Enum):
    ANY = "ANY"
    ANY_CHARGE = "ANY_CHARGE"
    NO_MATCHES = "NO_MATCHES"

    ERROR_INVALID_CREDENTIALS = "ERROR_INVALID_CREDENTIALS"
    ERROR_ANY_PROVIDER_MESSAGE = "ERROR_ANY_PROVIDER_MESSAGE"
    ERROR_CONNECTION_TO_PROVIDER = "ERROR_CONNECTION_TO_PROVIDER"
    EXTERNAL_RESOURCE_EMBED = "EXTERNAL_RESOURCE_EMBED"
    UNSUPPORTED_DEMO_RESULT = "UNSUPPORTED_DEMO_RESULT"


class DemoResultIdentityCheckResult(Enum):
    NO_MATCHES = "NO_MATCHES"
    ONE_NAME_ADDRESS_MATCH = "ONE_NAME_ADDRESS_MATCH"
    ONE_NAME_DOB_MATCH = "ONE_NAME_DOB_MATCH"
    TWO_NAME_ADDRESS_MATCH = "TWO_NAME_ADDRESS_MATCH"
    ONE_NAME_ADDRESS_ONE_NAME_DOB_MATCH = "ONE_NAME_ADDRESS_ONE_NAME_DOB_MATCH"
    ONE_NAME_ADDRESS_DOB_MATCH = "ONE_NAME_ADDRESS_DOB_MATCH"
    MORTALITY_MATCH = "MORTALITY_MATCH"
    ONE_NAME_ADDRESS_MORTALITY_MATCH = "ONE_NAME_ADDRESS_MORTALITY_MATCH"
    ONE_NAME_ADDRESS_ONE_NAME_DOB_MORTALITY_MATCH = "ONE_NAME_ADDRESS_ONE_NAME_DOB_MORTALITY_MATCH"


class DemoResultDocumentCheckResult(Enum):
    ERROR_UNSUPPORTED_DOCUMENT_TYPE = "ERROR_UNSUPPORTED_DOCUMENT_TYPE"
    DOCUMENT_IMAGE_CHECK_FAILURE = "DOCUMENT_IMAGE_CHECK_FAILURE"
    DOCUMENT_FORGERY_CHECK_FAILURE = "DOCUMENT_FORGERY_CHECK_FAILURE"
    DOCUMENT_NAME_FIELD_DIFFERENT = "DOCUMENT_NAME_FIELD_DIFFERENT"
    DOCUMENT_NAME_FIELD_UNREADABLE = "DOCUMENT_NAME_FIELD_UNREADABLE"
    DOCUMENT_DOB_FIELD_DIFFERENT = "DOCUMENT_DOB_FIELD_DIFFERENT"
    DOCUMENT_DOB_FIELD_UNREADABLE = "DOCUMENT_DOB_FIELD_UNREADABLE"
    DOCUMENT_ALL_PASS = "DOCUMENT_ALL_PASS"
    ERROR_INVALID_PROVIDER_REFERENCE = "ERROR_INVALID_PROVIDER_REFERENCE"
    ERROR_MISSING_CONTACT_DETAILS = "ERROR_MISSING_CONTACT_DETAILS"


class CompanyDataCheckResult(Enum):
    NO_DATA = "NO_DATA"
    ALL_DATA = "ALL_DATA"
    COMPANY_INACTIVE = "COMPANY_INACTIVE"
    COMPANY_COUNTRY_OF_INCORPORATION_MISMATCH = "COMPANY_COUNTRY_OF_INCORPORATION_MISMATCH"
    COMPANY_NAME_MISMATCH = "COMPANY_NAME_MISMATCH"
    COMPANY_NUMBER_MISMATCH = "COMPANY_NUMBER_MISMATCH"
    COMPANY_RESIGNED_OFFICER = "COMPANY_RESIGNED_OFFICER"
    COMPANY_FORMER_SHAREHOLDER = "COMPANY_FORMER_SHAREHOLDER"
    COMPANY_OFFICER_WITH_MULTIPLE_ROLES = "COMPANY_OFFICER_WITH_MULTIPLE_ROLES"
    COMPANY_SHAREHOLDER_WITH_100_PERCENT_OWNERSHIP = "COMPANY_SHAREHOLDER_WITH_100_PERCENT_OWNERSHIP"
    COMPANY_SHAREHOLDER_WITH_SIGNIFICANT_CONTROL = "COMPANY_SHAREHOLDER_WITH_SIGNIFICANT_CONTROL"
    COMPANY_INDIVIDUAL_OF_SIGNIFICANT_CONTROL = "COMPANY_INDIVIDUAL_OF_SIGNIFICANT_CONTROL"
    COMPANY_COMPANY_OF_SIGNIFICANT_CONTROL = "COMPANY_COMPANY_OF_SIGNIFICANT_CONTROL"
    COMPANY_ADDRESS_MATCH = "COMPANY_ADDRESS_MATCH"
    COMPANY_ADDRESS_MISMATCH = "COMPANY_ADDRESS_MISMATCH"
