
# This file was generated by 'versioneer.py' (0.28) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2024-06-22T23:28:43+0800",
 "dirty": false,
 "error": null,
 "full-revisionid": "7705d4ae1eb68523e87c4f2abf84026dae18b694",
 "version": "0.12.2.post1"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
