
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2024-06-23T16:58:38+0200",
 "dirty": false,
 "error": null,
 "full-revisionid": "ad014333ef1fcd7a991e0ee1771e1f5c37bc3184",
 "version": "1.0.10-rc1"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
