# Generated by Django 5.0.6 on 2024-05-16 05:50

import mdeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('django_medicio_dental', '0004_alter_post_content_alter_post_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='content',
            field=mdeditor.fields.MDTextField(verbose_name='Contents( {: .img-fluid} 추가)'),
        ),
    ]
