#ifndef NETGEN_VERSION_HPP_INCLUDED
#define NETGEN_VERSION_HPP_INCLUDED
#define NETGEN_VERSION "6.2.2404-10-g3b7dcdca"
#define NETGEN_VERSION_MAJOR 6
#define NETGEN_VERSION_MINOR 2
#define NETGEN_VERSION_PATCH 2404
#define NETGEN_VERSION_TWEAK 10
#define NETGEN_VERSION_HASH "g3b7dcdca"
#endif // NETGEN_VERSION_HPP_INCLUDED
