
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2024-06-19T16:50:08+0100",
 "dirty": false,
 "error": null,
 "full-revisionid": "e09b7c0d7da74aed708eb584e7d1ba82ca4ea1b5",
 "version": "v0.0"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
