
# This file was generated by 'versioneer.py' (0.19) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2024-06-19T10:31:34+0200",
 "dirty": false,
 "error": null,
 "full-revisionid": "55d2e624909fac3de2bb2c6149dd607347a1aa1c",
 "version": "2.5.3"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
