
# This file was generated by 'versioneer.py' (0.28) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2024-05-25T18:38:10+0200",
 "dirty": false,
 "error": null,
 "full-revisionid": "b54f455803e889c3487b2fa30fb01811c9ad3c6a",
 "version": "0.15.0"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
