
# This file was generated by 'versioneer.py' (0.28) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2024-06-07T14:34:43+0800",
 "dirty": false,
 "error": null,
 "full-revisionid": "2c7f818a8677646f616891378127409acc6d3209",
 "version": "3.0.9"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
