# Generated by Django 5.0.2 on 2024-03-26 22:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "artd_partner",
            "0005_alter_coworker_created_at_alter_coworker_updated_at_and_more",
        ),
        (
            "artd_product",
            "0013_rename_secondary_mini_image_category_secondary_mini_image",
        ),
        ("artd_shopify", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ShopifyTag",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.BooleanField(
                        default=True,
                        help_text="Designates whether this record is active or not.",
                        verbose_name="status",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="Date time on which the object was created.",
                        verbose_name="created at",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="Date time on which the object was last updated.",
                        verbose_name="updated at",
                    ),
                ),
                (
                    "tag",
                    models.CharField(
                        help_text="Shopify Tag.", max_length=255, verbose_name="tag"
                    ),
                ),
                (
                    "artd_partner",
                    models.ForeignKey(
                        help_text="ArtD Partner associated with this tag.",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="artd_partner.partner",
                        verbose_name="artd partner",
                    ),
                ),
                (
                    "category",
                    models.ForeignKey(
                        blank=True,
                        help_text="ArtD Category associated with this tag.",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="artd_product.category",
                        verbose_name="category",
                    ),
                ),
            ],
            options={
                "verbose_name": "Shopify Tag",
                "verbose_name_plural": "Shopify Tags",
            },
        ),
    ]
