
# This file was generated by 'versioneer.py' (0.29) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2024-06-20T19:32:18+0200",
 "dirty": false,
 "error": null,
 "full-revisionid": "0a4345e80f73eebbf7eca85fe981444a7df29037",
 "version": "1.0.12"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
