
# This file was generated by 'versioneer.py' (0.28) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2024-06-19T19:18:49+0200",
 "dirty": false,
 "error": null,
 "full-revisionid": "cd93c33c583f1f1a12e7d5e437c8fca38d7a64a3",
 "version": "1.1.4"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
