
# This file was generated by 'versioneer.py' (0.23) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2024-06-19T09:40:09+0800",
 "dirty": false,
 "error": null,
 "full-revisionid": "08d572839ede5d087e49d4dfadba033e512528df",
 "version": "1.3.2rc1"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
