
# This file was generated by 'versioneer.py' (0.28) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2024-06-21T15:34:17+0800",
 "dirty": false,
 "error": null,
 "full-revisionid": "5cef7c3d4bb0c5208d262fc3ffb7d7083724de1c",
 "version": "0.12.2"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
