# Generated by Django 5.0.2 on 2024-03-27 01:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "artd_partner",
            "0005_alter_coworker_created_at_alter_coworker_updated_at_and_more",
        ),
        ("artd_shopify", "0002_shopifytag"),
    ]

    operations = [
        migrations.CreateModel(
            name="ShopifyRootTag",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.BooleanField(
                        default=True,
                        help_text="Designates whether this record is active or not.",
                        verbose_name="status",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="Date time on which the object was created.",
                        verbose_name="created at",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="Date time on which the object was last updated.",
                        verbose_name="updated at",
                    ),
                ),
                (
                    "root_tag",
                    models.CharField(
                        help_text="Shopify Root Tag.",
                        max_length=255,
                        verbose_name="root tag",
                    ),
                ),
                (
                    "partner",
                    models.ForeignKey(
                        help_text="ArtD Partner associated with this tag.",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="artd_partner.partner",
                        verbose_name="partner",
                    ),
                ),
            ],
            options={
                "verbose_name": "Shopify Root Tag",
                "verbose_name_plural": "Shopify Root Tags",
            },
        ),
    ]
