# Generated by Django 5.0.2 on 2024-03-27 01:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "artd_product",
            "0013_rename_secondary_mini_image_category_secondary_mini_image",
        ),
        ("artd_shopify", "0003_shopifyroottag"),
    ]

    operations = [
        migrations.RenameField(
            model_name="shopifyroottag",
            old_name="partner",
            new_name="artd_partner",
        ),
        migrations.AddField(
            model_name="shopifyroottag",
            name="category",
            field=models.ForeignKey(
                blank=True,
                help_text="ArtD Category associated with this tag.",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="artd_product.category",
                verbose_name="category",
            ),
        ),
    ]
