
# This file was generated by 'versioneer.py' (0.29) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2024-06-20T15:29:42+0200",
 "dirty": true,
 "error": null,
 "full-revisionid": "db1f54669f4e712bff72abe3fb86ca2194ef4f21",
 "version": "0.9.2"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
