
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2024-06-21T09:51:59-0400",
 "dirty": false,
 "error": null,
 "full-revisionid": "065e582194213b50c6515a65e3110b36f5226d64",
 "version": "2024.6.21"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
