
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2024-06-19T17:57:42+0100",
 "dirty": false,
 "error": null,
 "full-revisionid": "15c4c829732b08106eb5d59ae1bb76618e09c34d",
 "version": "0.5.33"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
