# coding: utf-8

"""
    LEO Station Keeping API

    This mission allows to estimate the cost of station keeping maneuvers needed  to counter the effects of the atmospheric drag on the semi-major axis of a  spacecraft in low Earth orbit (up to an altitude of 1000 km).   <b>CHANGELOG</b> <ul>   <li><b>1.0.0</b> - 2024-06-07 - First version of the API</li> </ul> 

    The version of the OpenAPI document: 1.0.5
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import json
from enum import Enum
from typing_extensions import Self


class ThrustArcsPositions(str, Enum):
    """
    ThrustArcsPositions
    """

    """
    allowed enum values
    """
    ASCENDING_AND_DESCENDING_NODES = 'ASCENDING_AND_DESCENDING_NODES'
    ASCENDING_NODE = 'ASCENDING_NODE'
    DESCENDING_NODE = 'DESCENDING_NODE'
    CUSTOM = 'CUSTOM'
    APOGEE_AND_PERIGEE = 'APOGEE_AND_PERIGEE'
    APOGEE = 'APOGEE'
    PERIGEE = 'PERIGEE'
    ASCENDING_AND_DESCENDING_ANTINODES = 'ASCENDING_AND_DESCENDING_ANTINODES'
    ASCENDING_ANTINODE = 'ASCENDING_ANTINODE'
    DESCENDING_ANTINODE = 'DESCENDING_ANTINODE'
    MEAN_LONGITUDE = 'MEAN_LONGITUDE'

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Create an instance of ThrustArcsPositions from a JSON string"""
        return cls(json.loads(json_str))


