# Autogenerated by devscripts/update-version.py

__version__ = '2024.06.20.232815'

RELEASE_GIT_HEAD = '7aa322c02cec54eb77154a89da7e400194f0bd03'

VARIANT = 'pip'

UPDATE_HINT = 'You installed yt-dlp with pip or using the wheel from PyPi; Use that to update'

CHANNEL = 'nightly'

ORIGIN = 'yt-dlp/yt-dlp-nightly-builds'

_pkg_version = '2024.06.20.232815dev'
