# Generated by Django 4.2.4 on 2023-10-21 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ShortenedURL',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original_url', models.URLField(max_length=300, db_index=True)),
                ('short_url', models.CharField(max_length=60, unique=True)),
                ('created_dtm', models.DateTimeField(auto_now_add=True)),
                ('updated_dtm', models.DateTimeField(auto_now=True)),
                ('unique_id', models.CharField(db_index=True, max_length=30, unique=True)),
                ('hit_count', models.IntegerField(default=0)),
                ('expires_at', models.DateTimeField(null=True)),
                ('domain_name', models.CharField(max_length=100, null=True)),
                ('base_scheme', models.CharField(max_length=30, null=True)),
                ('base_domain', models.CharField(max_length=100, null=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
    ]
