# Generated by Django 5.0.2 on 2024-05-23 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='mbank_number',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Номер мобильного банка'),
        ),
    ]
