# Copyright 2023 Akretion - Raphaël Valyi <raphael.valyi@akretion.com>
# License LGPL-3.0 or later (https://www.gnu.org/licenses/lgpl-3.0.en.html).
# Generated by https://github.com/akretion/xsdata-odoo
#
import textwrap
from odoo import fields, models

from .evento_cte_tipos_basico_v4_00 import Tevento

__NAMESPACE__ = "http://www.portalfiscal.inf.br/cte"
