# Generated by Django 3.2.25 on 2024-06-19 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0041_uploadedfile_chatbot_description_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='chatsession',
            name='cluster_id',
        ),
        migrations.RemoveField(
            model_name='chatsession',
            name='file_id',
        ),
        migrations.RemoveField(
            model_name='chatsession',
            name='negative_feedback_count',
        ),
        migrations.RemoveField(
            model_name='chatsession',
            name='positive_count',
        ),
        migrations.RemoveField(
            model_name='chatsession',
            name='question_asked_time',
        ),
        migrations.RemoveField(
            model_name='chatsession',
            name='retrieval_count',
        ),
        migrations.RemoveField(
            model_name='chatsession',
            name='session_id',
        ),
        migrations.RemoveField(
            model_name='chatsession',
            name='session_start_time',
        ),
        migrations.RemoveField(
            model_name='chatsession',
            name='user',
        ),
        migrations.RemoveField(
            model_name='chatsession',
            name='user_identifier',
        ),
        migrations.RemoveField(
            model_name='chatsession',
            name='verification_count',
        ),
        migrations.RemoveField(
            model_name='chatsession',
            name='verified_by',
        ),
        migrations.RemoveField(
            model_name='feedback',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='feedback',
            name='session_id',
        ),
        migrations.RemoveField(
            model_name='feedback',
            name='user_identifier',
        ),
        migrations.RemoveField(
            model_name='similarquestion',
            name='cluster_id',
        ),
        migrations.RemoveField(
            model_name='similarquestion',
            name='file_id',
        ),
        migrations.RemoveField(
            model_name='similarquestion',
            name='question_asked_time',
        ),
        migrations.RemoveField(
            model_name='similarquestion',
            name='session_id',
        ),
        migrations.RemoveField(
            model_name='similarquestion',
            name='session_start_time',
        ),
        migrations.RemoveField(
            model_name='similarquestion',
            name='user_session_id',
        ),
        migrations.AddField(
            model_name='chatsession',
            name='user_name',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='similarquestion',
            name='user_name',
            field=models.CharField(max_length=255),
        ),
        migrations.DeleteModel(
            name='UploadedFile',
        ),
    ]
