class UnknownArgumentException(Exception):
    def __init__(self, *args: object) -> None: ...

class NameMustBeANSISQLIdentifierException(Exception):
    def __init__(self, *args: object) -> None: ...

class ObjectAlreadyExistsException(Exception):
    def __init__(self, *args: object) -> None: ...

class AttributeAlreadySetException(Exception):
    def __init__(self, *args: object) -> None: ...

class ObjectDoesntExistException(Exception):
    def __init__(self, *args: object) -> None: ...

class DatasetDoesntExistException(ObjectDoesntExistException):
    def __init__(self, *args: object) -> None: ...

class DatastoreDoesntExistException(ObjectDoesntExistException):
    def __init__(self, *args: object) -> None: ...

class WorkspaceDoesntExistException(ObjectDoesntExistException):
    def __init__(self, *args: object) -> None: ...

class StoragePolicyFromDifferentZone(Exception):
    def __init__(self, *args: object) -> None: ...
