
# This file was generated by 'versioneer.py' (0.28) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2024-06-21T18:03:41+0200",
 "dirty": false,
 "error": null,
 "full-revisionid": "28431219911fe4c149aa07736e2e4e45f3a28f57",
 "version": "2.5.1"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
