
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2024-06-21T11:03:22-0400",
 "dirty": false,
 "error": null,
 "full-revisionid": "e2ada58d1219ecdd4ce6b9a59d987007272d5f7f",
 "version": "2024.6.21.2"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
