from setuptools import setup, find_packages

setup(
    name='bunda',
    version='0.1',
    packages=find_packages(),
       install_requires=[
        'appnope',
        'asttokens',
        'comm',
        'debugpy',
        'decorator',
        'executing',
        'ipykernel',
        'ipython',
        'jedi',
        'jupyter_client',
        'jupyter_core',
        'matplotlib-inline',
        'nest-asyncio',
        'numpy',
        'packaging',
        'parso',
        'pexpect',
        'platformdirs',
        'prompt_toolkit',
        'psutil',
        'ptyprocess',
        'pure-eval',
        'py4j',
        'Pygments',
        'pyspark',
        'python-dateutil',
        'pyzmq',
        'setuptools',
        'six',
        'stack-data',
        'tornado',
        'traitlets',
        'wcwidth',
    ],
    author='bunda',
    author_email='bunda@bunda.com',
    description='bunda',
    url='https://github.com/bunda/bunda',
    classifiers=[
        'Programming Language :: Python :: 3',
        'License :: OSI Approved :: MIT License',
        'Operating System :: OS Independent',
    ],
)
