dlite_INSTALL_ROOT = '/project/python/build/temp.linux-i686-cpython-37/{project}/python/build/lib.manylinux2014_x86_64-3.7'
dlite_BUILD_ROOT = '/project/python/build/temp.linux-i686-cpython-37'

dlite_PATH = ''
dlite_LD_LIBRARY_PATH = '/project/python/build/temp.linux-i686-cpython-37/src;/project/python/build/temp.linux-i686-cpython-37/src/utils;/project/python/build/temp.linux-i686-cpython-37/src/pyembed'
dlite_PYTHONPATH = '/project/python/build/temp.linux-i686-cpython-37/bindings/python'
dlite_STORAGE_PLUGINS = '/project/python/build/temp.linux-i686-cpython-37/storages/json;/project/python/build/temp.linux-i686-cpython-37/storages/rdf;/project/python/build/temp.linux-i686-cpython-37/storages/python'
dlite_MAPPING_PLUGINS = ''
dlite_PYTHON_STORAGE_PLUGINS = '/project/storages/python/python-storage-plugins'
dlite_PYTHON_MAPPING_PLUGINS = '/project/bindings/python/python-mapping-plugins'
dlite_TEMPLATES = '/project/tools/templates'
dlite_STORAGES = '/project/examples/storages/*.json'
