
# This file was generated by 'versioneer.py' (0.28) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2024-05-21T17:47:38+0800",
 "dirty": false,
 "error": null,
 "full-revisionid": "d7fb4192e172f25e72d55a5dcc1fd974cfe2e1ae",
 "version": "3.0.7.1"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
