from .infoinsta import Info_Insta
from .chat import GPT
from .ktkt import kt
from .tik_tok import Tik_Tok
from .info_tik import Info_Tik
from .pryer import prayer_times
from .insta import instagram
from .search_pinterset import Search_Pinterest
from .soundcloud import Sound_Cloud
from .youtu import YouTube_Download
from .twitter import Twitter_Download
from .restinsta import Rest_Instagram
from .facebook import FaceBook_Download
from .pinterest import Pinterest_Download
from .spotify import Spotify_Download
#from .kwai import Kwai_Download
#from .snapchat import SnapChat_Download
#from .likee import Likee_Download
#from .threads import Threads_Download