
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2024-06-21T10:38:45-0400",
 "dirty": false,
 "error": null,
 "full-revisionid": "9c5a57ec9c67a88abbca4b864d07b6090428cf3f",
 "version": "2024.6.21"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
