# Generated by Django 5.0.6 on 2024-06-14 05:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('django_medicio_dental', '0006_alter_post_content'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Post',
        ),
    ]
