
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2024-06-19T14:45:00+0100",
 "dirty": false,
 "error": null,
 "full-revisionid": "cf493cd3e7dba50c4dac99d4ace6b4e7947e84fc",
 "version": "0.5.31"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
