
# This file was generated by 'versioneer.py' (0.19) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2024-06-21T17:02:44+0200",
 "dirty": false,
 "error": null,
 "full-revisionid": "f2b18a4eca6436f8cbda18aeb3fe5cecdce01538",
 "version": "2.6.1"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
