
# This file was generated by 'versioneer.py' (0.19) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2024-06-21T05:21:18-0700",
 "dirty": false,
 "error": null,
 "full-revisionid": "a2a7e961030ec348e6e285ccbcb786f2e7cfd193",
 "version": "4.1.51"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
