# coding: utf-8

"""
    Synapse DB

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.1.13
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from syndb_api_client.api.auth_api import AuthApi


class TestAuthApi(unittest.TestCase):
    """AuthApi unit test stubs"""

    def setUp(self) -> None:
        self.api = AuthApi()

    def tearDown(self) -> None:
        pass

    def test_auth_database_login_user_auth_database_login_post(self) -> None:
        """Test case for auth_database_login_user_auth_database_login_post

        Auth:Database.Login
        """
        pass

    def test_auth_database_logout_user_auth_database_logout_post(self) -> None:
        """Test case for auth_database_logout_user_auth_database_logout_post

        Auth:Database.Logout
        """
        pass

    def test_oauth_oauth2_database_authorize_user_auth_orcid_authorize_get(self) -> None:
        """Test case for oauth_oauth2_database_authorize_user_auth_orcid_authorize_get

        Oauth:Oauth2.Database.Authorize
        """
        pass

    def test_oauth_oauth2_database_callback_user_auth_orcid_callback_get(self) -> None:
        """Test case for oauth_oauth2_database_callback_user_auth_orcid_callback_get

        Oauth:Oauth2.Database.Callback
        """
        pass


if __name__ == "__main__":
    unittest.main()
