# coding: utf-8

"""
    Synapse DB

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.1.13
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from syndb_api_client.models.mutation_model_just_read import MutationModelJustRead


class TestMutationModelJustRead(unittest.TestCase):
    """MutationModelJustRead unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> MutationModelJustRead:
        """Test MutationModelJustRead
        include_option is a boolean, when False only required
        params are included, when True both required and
        optional params are included"""
        # uncomment below to create an instance of `MutationModelJustRead`
        """
        model = MutationModelJustRead()
        if include_optional:
            return MutationModelJustRead(
                gene = '',
                expression = 'knock-out'
            )
        else:
            return MutationModelJustRead(
                gene = '',
                expression = 'knock-out',
        )
        """

    def testMutationModelJustRead(self):
        """Test MutationModelJustRead"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)


if __name__ == "__main__":
    unittest.main()
