# coding: utf-8

"""
    Synapse DB

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.1.13
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from syndb_api_client.models.pre_signed_s3_schema import PreSignedS3Schema


class TestPreSignedS3Schema(unittest.TestCase):
    """PreSignedS3Schema unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> PreSignedS3Schema:
        """Test PreSignedS3Schema
        include_option is a boolean, when False only required
        params are included, when True both required and
        optional params are included"""
        # uncomment below to create an instance of `PreSignedS3Schema`
        """
        model = PreSignedS3Schema()
        if include_optional:
            return PreSignedS3Schema(
                upload_url = '',
                fields = syndb_api_client.models.fields.Fields()
            )
        else:
            return PreSignedS3Schema(
                upload_url = '',
                fields = syndb_api_client.models.fields.Fields(),
        )
        """

    def testPreSignedS3Schema(self):
        """Test PreSignedS3Schema"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)


if __name__ == "__main__":
    unittest.main()
