# coding: utf-8

"""
    Synapse DB

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.1.13
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from syndb_api_client.models.user_metadata_response import UserMetadataResponse


class TestUserMetadataResponse(unittest.TestCase):
    """UserMetadataResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> UserMetadataResponse:
        """Test UserMetadataResponse
        include_option is a boolean, when False only required
        params are included, when True both required and
        optional params are included"""
        # uncomment below to create an instance of `UserMetadataResponse`
        """
        model = UserMetadataResponse()
        if include_optional:
            return UserMetadataResponse(
                publication_dois = [
                    ''
                    ],
                animal = [
                    syndb_api_client.models.animal_model_just_read.AnimalModelJustRead(
                        species = '', 
                        cultural_name = '', )
                    ],
                mutation = [
                    syndb_api_client.models.mutation_model_just_read.MutationModelJustRead(
                        gene = '', 
                        expression = 'knock-out', )
                    ],
                brain_region = [
                    syndb_api_client.models.brain_region_just_read.BrainRegionJustRead(
                        brain_structure = 'amygdaloid complex', 
                        direction = 'anterior', )
                    ],
                microscopy_names = [
                    ''
                    ],
                all_datasets = {
                    'key' : ''
                    },
                modifiable_datasets = [
                    56
                    ],
                upload_incomplete_uuid_to_label = {
                    'key' : ''
                    }
            )
        else:
            return UserMetadataResponse(
                all_datasets = {
                    'key' : ''
                    },
                modifiable_datasets = [
                    56
                    ],
                upload_incomplete_uuid_to_label = {
                    'key' : ''
                    },
        )
        """

    def testUserMetadataResponse(self):
        """Test UserMetadataResponse"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)


if __name__ == "__main__":
    unittest.main()
