# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: resemble/v1alpha1/inspect/inspect.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.api import annotations_pb2 as google_dot_api_dot_annotations__pb2
from google.protobuf import struct_pb2 as google_dot_protobuf_dot_struct__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\'resemble/v1alpha1/inspect/inspect.proto\x12\x19resemble.v1alpha1.inspect\x1a\x1cgoogle/api/annotations.proto\x1a\x1cgoogle/protobuf/struct.proto\"\x15\n\x13GetAllActorsRequest\"?\n\x14GetAllActorsResponse\x12\'\n\x06\x61\x63tors\x18\x01 \x01(\x0b\x32\x17.google.protobuf.Struct2\xb6\x01\n\x07Inspect\x12\xaa\x01\n\x0cGetAllActors\x12..resemble.v1alpha1.inspect.GetAllActorsRequest\x1a/.resemble.v1alpha1.inspect.GetAllActorsResponse\"7\x82\xd3\xe4\x93\x02\x31\"//resemble.v1alpha1.inspect.Inspect/GetAllActors0\x01\x62\x06proto3')



_GETALLACTORSREQUEST = DESCRIPTOR.message_types_by_name['GetAllActorsRequest']
_GETALLACTORSRESPONSE = DESCRIPTOR.message_types_by_name['GetAllActorsResponse']
GetAllActorsRequest = _reflection.GeneratedProtocolMessageType('GetAllActorsRequest', (_message.Message,), {
  'DESCRIPTOR' : _GETALLACTORSREQUEST,
  '__module__' : 'resemble.v1alpha1.inspect.inspect_pb2'
  # @@protoc_insertion_point(class_scope:resemble.v1alpha1.inspect.GetAllActorsRequest)
  })
_sym_db.RegisterMessage(GetAllActorsRequest)

GetAllActorsResponse = _reflection.GeneratedProtocolMessageType('GetAllActorsResponse', (_message.Message,), {
  'DESCRIPTOR' : _GETALLACTORSRESPONSE,
  '__module__' : 'resemble.v1alpha1.inspect.inspect_pb2'
  # @@protoc_insertion_point(class_scope:resemble.v1alpha1.inspect.GetAllActorsResponse)
  })
_sym_db.RegisterMessage(GetAllActorsResponse)

_INSPECT = DESCRIPTOR.services_by_name['Inspect']
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _INSPECT.methods_by_name['GetAllActors']._options = None
  _INSPECT.methods_by_name['GetAllActors']._serialized_options = b'\202\323\344\223\0021\"//resemble.v1alpha1.inspect.Inspect/GetAllActors'
  _GETALLACTORSREQUEST._serialized_start=130
  _GETALLACTORSREQUEST._serialized_end=151
  _GETALLACTORSRESPONSE._serialized_start=153
  _GETALLACTORSRESPONSE._serialized_end=216
  _INSPECT._serialized_start=219
  _INSPECT._serialized_end=401
# @@protoc_insertion_point(module_scope)
