""" This file is automatically generated from "mitsuba.conf" using the script
    "resources/configure.py". Please do not attempt to change it manually,
    as any changes will be overwritten."""

PYTHON_EXECUTABLE = r"/private/var/folders/n0/93pmqpw54kn_g2qbs9kqxrxh0000gn/T/cibw-run-vussnt20/cp39-macosx_x86_64/build/venv/bin/python"
MI_DEFAULT_VARIANT = ''
MI_VARIANTS = ['scalar_mono', 'scalar_mono_double', 'scalar_rgb', 'scalar_spectral', 'llvm_ad_rgb']
DRJIT_VERSION_REQUIREMENT = '0.4.4'
CXX_COMPILER = 'AppleClang 15.0.0.15000040'
