# coding: utf-8

"""
    FDS API

    API for Flight Dynamics System

    The version of the OpenAPI document: 1.1.0
    Contact: contact@exotrail.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from spacetower_python_client.api.thruster_api import ThrusterApi


class TestThrusterApi(unittest.TestCase):
    """ThrusterApi unit test stubs"""

    def setUp(self) -> None:
        self.api = ThrusterApi()

    def tearDown(self) -> None:
        pass

    def test_create_chemical_thruster(self) -> None:
        """Test case for create_chemical_thruster

        """
        pass

    def test_create_electrical_thruster(self) -> None:
        """Test case for create_electrical_thruster

        """
        pass

    def test_delete_thruster(self) -> None:
        """Test case for delete_thruster

        """
        pass

    def test_retrieve_all_thrusters(self) -> None:
        """Test case for retrieve_all_thrusters

        """
        pass

    def test_retrieve_thruster(self) -> None:
        """Test case for retrieve_thruster

        """
        pass


if __name__ == '__main__':
    unittest.main()
