# coding: utf-8

"""
    FDS API

    API for Flight Dynamics System

    The version of the OpenAPI document: 1.1.0
    Contact: contact@exotrail.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from spacetower_python_client.models.radar_measurements_request_dto import RadarMeasurementsRequestDto

class TestRadarMeasurementsRequestDto(unittest.TestCase):
    """RadarMeasurementsRequestDto unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> RadarMeasurementsRequestDto:
        """Test RadarMeasurementsRequestDto
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `RadarMeasurementsRequestDto`
        """
        model = RadarMeasurementsRequestDto()
        if include_optional:
            return RadarMeasurementsRequestDto(
                azimuth_standard_deviation = 1.337,
                elevation_standard_deviation = 1.337,
                generation_step = 56,
                ground_station_id = '',
                id = '',
                range_rate_standard_deviation = 1.337,
                range_standard_deviation = 1.337,
                two_way_measurement = True
            )
        else:
            return RadarMeasurementsRequestDto(
                azimuth_standard_deviation = 1.337,
                elevation_standard_deviation = 1.337,
                generation_step = 56,
                ground_station_id = '',
                range_rate_standard_deviation = 1.337,
                range_standard_deviation = 1.337,
                two_way_measurement = True,
        )
        """

    def testRadarMeasurementsRequestDto(self):
        """Test RadarMeasurementsRequestDto"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
