# coding: utf-8

"""
    FDS API

    API for Flight Dynamics System

    The version of the OpenAPI document: 1.1.0
    Contact: contact@exotrail.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from spacetower_python_client.models.reflectivity_coefficient_estimation_request_input_dto import ReflectivityCoefficientEstimationRequestInputDto

class TestReflectivityCoefficientEstimationRequestInputDto(unittest.TestCase):
    """ReflectivityCoefficientEstimationRequestInputDto unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ReflectivityCoefficientEstimationRequestInputDto:
        """Test ReflectivityCoefficientEstimationRequestInputDto
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ReflectivityCoefficientEstimationRequestInputDto`
        """
        model = ReflectivityCoefficientEstimationRequestInputDto()
        if include_optional:
            return ReflectivityCoefficientEstimationRequestInputDto(
                id = '',
                parameter_standard_deviation = 0.0,
                process_noise_standard_deviation = 0.0
            )
        else:
            return ReflectivityCoefficientEstimationRequestInputDto(
                parameter_standard_deviation = 0.0,
                process_noise_standard_deviation = 0.0,
        )
        """

    def testReflectivityCoefficientEstimationRequestInputDto(self):
        """Test ReflectivityCoefficientEstimationRequestInputDto"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
