# coding: utf-8

"""
    FDS API

    API for Flight Dynamics System

    The version of the OpenAPI document: 1.1.0
    Contact: contact@exotrail.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from spacetower_python_client.api.orbit_data_message_request_api import OrbitDataMessageRequestApi


class TestOrbitDataMessageRequestApi(unittest.TestCase):
    """OrbitDataMessageRequestApi unit test stubs"""

    def setUp(self) -> None:
        self.api = OrbitDataMessageRequestApi()

    def tearDown(self) -> None:
        pass

    def test_create_oem_request(self) -> None:
        """Test case for create_oem_request

        """
        pass

    def test_delete_orbit_data_message_request(self) -> None:
        """Test case for delete_orbit_data_message_request

        """
        pass

    def test_retrieve_all4(self) -> None:
        """Test case for retrieve_all4

        """
        pass

    def test_retrieve_orbit_data_message_request_by_id(self) -> None:
        """Test case for retrieve_orbit_data_message_request_by_id

        """
        pass


if __name__ == '__main__':
    unittest.main()
