# coding: utf-8

"""
    FDS API

    API for Flight Dynamics System

    The version of the OpenAPI document: 1.1.0
    Contact: contact@exotrail.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from spacetower_python_client.models.oem_request_dto import OemRequestDto

class TestOemRequestDto(unittest.TestCase):
    """OemRequestDto unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> OemRequestDto:
        """Test OemRequestDto
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `OemRequestDto`
        """
        model = OemRequestDto()
        if include_optional:
            return OemRequestDto(
                creator = '',
                ephemerides_step = 1.337,
                frame = 'EME2000',
                id = '',
                object_id = '',
                object_name = '',
                write_acceleration = True,
                write_covariance = True
            )
        else:
            return OemRequestDto(
                creator = '',
                ephemerides_step = 1.337,
                frame = 'EME2000',
                object_id = '',
                object_name = '',
        )
        """

    def testOemRequestDto(self):
        """Test OemRequestDto"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
