# coding: utf-8

"""
    FDS API

    API for Flight Dynamics System

    The version of the OpenAPI document: 1.1.0
    Contact: contact@exotrail.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from spacetower_python_client.api.roadmap_action_api import RoadmapActionApi


class TestRoadmapActionApi(unittest.TestCase):
    """RoadmapActionApi unit test stubs"""

    def setUp(self) -> None:
        self.api = RoadmapActionApi()

    def tearDown(self) -> None:
        pass

    def test_create_attitude_action(self) -> None:
        """Test case for create_attitude_action

        """
        pass

    def test_create_firing_action(self) -> None:
        """Test case for create_firing_action

        """
        pass

    def test_create_quaternion_action(self) -> None:
        """Test case for create_quaternion_action

        """
        pass

    def test_delete_roadmap_action(self) -> None:
        """Test case for delete_roadmap_action

        """
        pass

    def test_retrieve_all_roadmap_actions(self) -> None:
        """Test case for retrieve_all_roadmap_actions

        """
        pass

    def test_retrieve_roadmap_action(self) -> None:
        """Test case for retrieve_roadmap_action

        """
        pass


if __name__ == '__main__':
    unittest.main()
