# coding: utf-8

"""
    FDS API

    API for Flight Dynamics System

    The version of the OpenAPI document: 1.1.0
    Contact: contact@exotrail.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from spacetower_python_client.models.outlier_manager_settings_dto import OutlierManagerSettingsDto

class TestOutlierManagerSettingsDto(unittest.TestCase):
    """OutlierManagerSettingsDto unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> OutlierManagerSettingsDto:
        """Test OutlierManagerSettingsDto
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `OutlierManagerSettingsDto`
        """
        model = OutlierManagerSettingsDto()
        if include_optional:
            return OutlierManagerSettingsDto(
                max_number_of_consecutive_outliers = 56,
                outlier_max_scale = 1.337,
                outlier_warmup_iterations = 56
            )
        else:
            return OutlierManagerSettingsDto(
                outlier_max_scale = 1.337,
                outlier_warmup_iterations = 56,
        )
        """

    def testOutlierManagerSettingsDto(self):
        """Test OutlierManagerSettingsDto"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
