# coding: utf-8

"""
    FDS API

    API for Flight Dynamics System

    The version of the OpenAPI document: 1.1.0
    Contact: contact@exotrail.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from spacetower_python_client.models.optical_telemetry_dto import OpticalTelemetryDto

class TestOpticalTelemetryDto(unittest.TestCase):
    """OpticalTelemetryDto unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> OpticalTelemetryDto:
        """Test OpticalTelemetryDto
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `OpticalTelemetryDto`
        """
        model = OpticalTelemetryDto()
        if include_optional:
            return OpticalTelemetryDto(
                azimuth_standard_deviation = 1.337,
                dates = [
                    ''
                    ],
                elevation_standard_deviation = 1.337,
                ground_station_id = '',
                id = '',
                measurements = [
                    [
                        1.337
                        ]
                    ]
            )
        else:
            return OpticalTelemetryDto(
                azimuth_standard_deviation = 1.337,
                dates = [
                    ''
                    ],
                elevation_standard_deviation = 1.337,
                ground_station_id = '',
                measurements = [
                    [
                        1.337
                        ]
                    ],
        )
        """

    def testOpticalTelemetryDto(self):
        """Test OpticalTelemetryDto"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
