# coding: utf-8

"""
    FDS API

    API for Flight Dynamics System

    The version of the OpenAPI document: 1.1.0
    Contact: contact@exotrail.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from spacetower_python_client.api.ephemeris_request_controller_api import EphemerisRequestControllerApi


class TestEphemerisRequestControllerApi(unittest.TestCase):
    """EphemerisRequestControllerApi unit test stubs"""

    def setUp(self) -> None:
        self.api = EphemerisRequestControllerApi()

    def tearDown(self) -> None:
        pass

    def test_create_ephemeris_request(self) -> None:
        """Test case for create_ephemeris_request

        """
        pass

    def test_delete(self) -> None:
        """Test case for delete

        """
        pass

    def test_retrieve1(self) -> None:
        """Test case for retrieve1

        """
        pass

    def test_retrieve_all9(self) -> None:
        """Test case for retrieve_all9

        """
        pass


if __name__ == '__main__':
    unittest.main()
