# coding: utf-8

"""
    FDS API

    API for Flight Dynamics System

    The version of the OpenAPI document: 1.1.0
    Contact: contact@exotrail.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from spacetower_python_client.models.maneuver_generation_output_dto import ManeuverGenerationOutputDto

class TestManeuverGenerationOutputDto(unittest.TestCase):
    """ManeuverGenerationOutputDto unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ManeuverGenerationOutputDto:
        """Test ManeuverGenerationOutputDto
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ManeuverGenerationOutputDto`
        """
        model = ManeuverGenerationOutputDto()
        if include_optional:
            return ManeuverGenerationOutputDto(
                delta_eccentricity = 1.337,
                delta_inclination = 1.337,
                delta_semi_major_axis = 1.337,
                id = '',
                initial_orbital_state = spacetower_python_client.models.orbital_state_dto.OrbitalStateDto(
                    covariance_matrix_id = '', 
                    creation_date = '', 
                    fitted_tle = spacetower_python_client.models.tle.TLE(
                        line1 = '', 
                        line2 = '', ), 
                    id = '', 
                    mean_orbit_id = '', 
                    osculating_orbit_id = '', 
                    propagation_context_id = '', 
                    source = 'ORBIT_DETERMINATION', 
                    spacecraft_id = '', ),
                maximum_duration = 1.337,
                no_firing_date_intervals = [
                    spacetower_python_client.models.date_interval_dto.DateIntervalDto(
                        end = '', 
                        start = '', )
                    ],
                quaternion_step = 1.337,
                required_output_orbital_states = 'ALL',
                strategy = spacetower_python_client.models.maneuver_strategy_dto.ManeuverStrategyDto(
                    id = '', 
                    number_of_rest_orbits = 56, 
                    number_of_shift_orbits = 56, 
                    number_of_thrust_orbits = 56, 
                    orbital_duty_cycle = 1.337, 
                    stop_thrust_at_eclipse = True, 
                    thrust_arc_definition = 'DUTY_CYCLE', 
                    thrust_arc_duration = 1.337, 
                    thrust_arcs_number = 'ONE', 
                    thrust_arcs_position = 'ASCENDING_AND_DESCENDING_NODES', )
            )
        else:
            return ManeuverGenerationOutputDto(
        )
        """

    def testManeuverGenerationOutputDto(self):
        """Test ManeuverGenerationOutputDto"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
