# coding: utf-8

"""
    FDS API

    API for Flight Dynamics System

    The version of the OpenAPI document: 1.1.0
    Contact: contact@exotrail.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from spacetower_python_client.api.covariance_matrix_api import CovarianceMatrixApi


class TestCovarianceMatrixApi(unittest.TestCase):
    """CovarianceMatrixApi unit test stubs"""

    def setUp(self) -> None:
        self.api = CovarianceMatrixApi()

    def tearDown(self) -> None:
        pass

    def test_create_covariance_matrix(self) -> None:
        """Test case for create_covariance_matrix

        """
        pass

    def test_create_diagonal_covariance_matrix(self) -> None:
        """Test case for create_diagonal_covariance_matrix

        """
        pass

    def test_delete1(self) -> None:
        """Test case for delete1

        """
        pass

    def test_retrieve2(self) -> None:
        """Test case for retrieve2

        """
        pass

    def test_retrieve_all10(self) -> None:
        """Test case for retrieve_all10

        """
        pass


if __name__ == '__main__':
    unittest.main()
