# coding: utf-8

"""
    FDS API

    API for Flight Dynamics System

    The version of the OpenAPI document: 1.1.0
    Contact: contact@exotrail.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from spacetower_python_client.api.telemetry_api import TelemetryApi


class TestTelemetryApi(unittest.TestCase):
    """TelemetryApi unit test stubs"""

    def setUp(self) -> None:
        self.api = TelemetryApi()

    def tearDown(self) -> None:
        pass

    def test_create_gps_nmea_telemetry(self) -> None:
        """Test case for create_gps_nmea_telemetry

        """
        pass

    def test_create_gps_nmea_telemetry_raw(self) -> None:
        """Test case for create_gps_nmea_telemetry_raw

        """
        pass

    def test_create_gps_pv_telemetry(self) -> None:
        """Test case for create_gps_pv_telemetry

        """
        pass

    def test_create_optical_telemetry(self) -> None:
        """Test case for create_optical_telemetry

        """
        pass

    def test_create_radar_telemetry(self) -> None:
        """Test case for create_radar_telemetry

        """
        pass

    def test_delete_telemetry(self) -> None:
        """Test case for delete_telemetry

        """
        pass

    def test_retrieve(self) -> None:
        """Test case for retrieve

        """
        pass

    def test_retrieve_all5(self) -> None:
        """Test case for retrieve_all5

        """
        pass


if __name__ == '__main__':
    unittest.main()
