# coding: utf-8

"""
    FDS API

    API for Flight Dynamics System

    The version of the OpenAPI document: 1.1.0
    Contact: contact@exotrail.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from spacetower_python_client.models.attitude_action_dto import AttitudeActionDto

class TestAttitudeActionDto(unittest.TestCase):
    """AttitudeActionDto unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> AttitudeActionDto:
        """Test AttitudeActionDto
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `AttitudeActionDto`
        """
        model = AttitudeActionDto()
        if include_optional:
            return AttitudeActionDto(
                attitude_mode = 'PROGRADE',
                id = '',
                quaternions = [
                    spacetower_python_client.models.quaternion_action_dto.QuaternionActionDto(
                        id = '', 
                        q0 = 1.337, 
                        q1 = 1.337, 
                        q2 = 1.337, 
                        q3 = 1.337, 
                        transition_date = '', )
                    ],
                transition_date = ''
            )
        else:
            return AttitudeActionDto(
                attitude_mode = 'PROGRADE',
                transition_date = '',
        )
        """

    def testAttitudeActionDto(self):
        """Test AttitudeActionDto"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
