# coding: utf-8

"""
    FDS API

    API for Flight Dynamics System

    The version of the OpenAPI document: 1.1.0
    Contact: contact@exotrail.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from spacetower_python_client.models.ground_station_dto import GroundStationDto

class TestGroundStationDto(unittest.TestCase):
    """GroundStationDto unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> GroundStationDto:
        """Test GroundStationDto
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `GroundStationDto`
        """
        model = GroundStationDto()
        if include_optional:
            return GroundStationDto(
                altitude = 1.337,
                elevation_mask = [
                    [
                        1.337
                        ]
                    ],
                id = '',
                latitude = 1.337,
                longitude = 1.337,
                min_elevation = 1.337,
                name = ''
            )
        else:
            return GroundStationDto(
                altitude = 1.337,
                latitude = 1.337,
                longitude = 1.337,
                name = '',
        )
        """

    def testGroundStationDto(self):
        """Test GroundStationDto"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
