from typing import Literal

from _typeshed import Incomplete

from ..precision_timer_ext import CPrecisionTimer as CPrecisionTimer
from ..utilities import format_message as format_message

class PrecisionTimer:
    _supported_precisions: Incomplete
    _timer: Incomplete
    def __init__(self, precision: Literal["ns", "us", "ms", "s"] = ...) -> None: ...
    def __repr__(self) -> str: ...
    @property
    def elapsed(self) -> int: ...
    @property
    def precision(self) -> str: ...
    @property
    def supported_precisions(self) -> tuple[str, str, str, str]: ...
    def reset(self) -> None: ...
    def delay_noblock(self, delay: int, *, allow_sleep: bool = ...) -> None: ...
    def delay_block(self, delay: int, *, allow_sleep: bool = ...) -> None: ...
    def set_precision(self, precision: Literal["ns", "us", "ms", "s"]) -> None: ...
