
# This file was generated by 'versioneer.py' (0.29) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2024-06-20T09:22:38+0200",
 "dirty": true,
 "error": null,
 "full-revisionid": "b66062b1373619e9ddfa414ee4aa3af2c35c2fa9",
 "version": "1.1.4.post0.dev28"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
